= Обзор синтаксиса языка Java

Давайте начнём знакомство с языком Java! Перед вами простейшая программа "Здравствуй, мир".

[source,java]
----
// test/Hello.java
package test;
public class Hello {
    public static void main(String[] args) {
        System.out.println("Здравствуй, мир!);
    }
}
----

Язык Java отличается некоторой многословностью. 
Как видите, даже простая программа на этом языке содержит много всяких слов. 
Попробуем в них разобраться.

== Классы

Класс является главным элементом Java-программы!
Любая Java-программа всегда содержит хотя бы один класс, а любой код на Java находится внутри какого-то класса.

С помощью классов реализуется *парадигма программирования* ООП = объектно-ориентированное программирование. 
Обучение обычно начинают с процедурного программирования, краеугольным камнем которого
является разбиение задачи на подзадачи, после чего каждая подзадача реализуется как процедура или функция,
а задача в целом -- как главная функция.
В объектно-ориентированном программировании краеугольным камнем являются *понятия* или *объекты*, 
которые фигурируют в задаче. 
Программист, решая задачу, выделяет в ней наиболее важные понятия и реализует их в виде *класса*. 
Класс содержит *данные*, которые описывают понятия задачи, и *функции*, которые работают с этими данными.

В разделе 2 мы подробно рассмотрим определение понятия через класс,
а пока нам достаточно знать, что в языке Java любой код обязан находиться внутри класса.
Чтобы определить класс, нужно написать код вида
[source,java]
----
public class Hello {
    // Тело класса
}
----

Ключевое слово _public_ делает класс *открытым*, то есть доступным во всей программе. 
`Hello` является именем класса.

Язык Java придерживается ряда соглашений о структуре проекта.
В частности, все файлы с исходным кодом должны находится в директории, которая называется *Source root*
(переводится на русский примерно как "корневая директория исходного кода").
В проекте с использованием систем сборки Maven или Gradle директория Source root = `ProjectDir/src/main/java`.
В проекте без использования систем сборки всё проще: Source root = `ProjectDir/src`.
Содержимое же директории *Source root* определяется структорой *пакетов* (_package_).
Например:

[source,java]
----
// test/Hello.java
package test;
public class Hello {
}
----

Обратите внимание на директиву `package test` перед определением класса. 
Это означает, что файл `Hello.java` обязан находиться в директории `test`, которая, 
в свою очередь, должна являться поддиректорией Source root.
О классе `Hello` в этом случае говорят, что он находится в пакете `test`,
а *полное его имя* -- test.Hello.
Имя файла обязано совпадать с именем определённого в нём открытого класса
(отсюда, в частности, следует, что открытый класс в файле может быть определён лишь один).

[source,java]
----
// another/subpack/Some.java
package another.subpack;
public class Some {
}
----

Здесь класс `Some` находится в пакете `another.subpack`, 
его полное имя -- another.subpack.Some, он обязан находиться в файле `Some.java`,
а путь к этому файлу должен быть `another/subpack/Some.java`. 
Директория `another` должна быть поддиректорией Source root.

