= Обзор синтаксиса языка Java

Давайте начнём знакомство с языком Java! Перед вами простейшая программа "Здравствуй, мир".

[source,java]
----
// test/Hello.java
package test;
public class Hello {
    public static void main(String[] args) {
        System.out.println("Здравствуй, мир!);
    }
}
----

Язык Java отличается некоторой многословностью. 
Как видите, даже простая программа на этом языке содержит много всяких слов. 
Попробуем в них разобраться.

== Классы

Класс является главным элементом Java-программы!
Любая Java-программа всегда содержит хотя бы один класс, а любой код на Java находится внутри какого-то класса.

С помощью классов реализуется *парадигма программирования* ООП = объектно-ориентированное программирование. 
Обучение обычно начинают с процедурного программирования, краеугольным камнем которого
является разбиение задачи на подзадачи, после чего каждая подзадача реализуется как процедура или функция,
а задача в целом -- как главная функция.
В объектно-ориентированном программировании краеугольным камнем являются *понятия* или *объекты*, 
которые фигурируют в задаче. 
Программист, решая задачу, выделяет в ней наиболее важные понятия и реализует их в виде *класса*. 
Класс содержит *данные*, которые описывают понятия задачи, и *функции*, которые работают с этими данными.

В разделе 2 мы подробно рассмотрим определение понятия через класс,
а пока нам достаточно знать, что в языке Java любой код обязан находиться внутри класса.
Чтобы определить класс, нужно написать код вида
[source,java]
----
public class Hello {
    // Тело класса
}
----

Ключевое слово _public_ делает класс *открытым*, то есть доступным во всей программе. 
`Hello` является именем класса.

== Пакеты

Язык Java придерживается ряда соглашений о структуре проекта.
В частности, все файлы с исходным кодом должны находится в директории, которая называется *Source root*
(переводится на русский примерно как "корневая директория исходного кода").
В проекте с использованием систем сборки Maven или Gradle директория Source root = `ProjectDir/src/main/java`.
В проекте без использования систем сборки всё проще: Source root = `ProjectDir/src`.
Содержимое же директории *Source root* определяется структорой *пакетов* (_package_).
Например:

[source,java]
----
// test/Hello.java
package test;
public class Hello {
}
----

Обратите внимание на директиву `package test` перед определением класса. 
Это означает, что файл `Hello.java` обязан находиться в директории `test`, которая, 
в свою очередь, должна являться поддиректорией Source root.
О классе `Hello` в этом случае говорят, что он находится в пакете `test`,
а *полное его имя* -- test.Hello.
Имя файла обязано совпадать с именем определённого в нём открытого класса
(отсюда, в частности, следует, что открытый класс в файле может быть определён лишь один).

[source,java]
----
// another/subpack/Some.java
package another.subpack;
public class Some {
}
----

Здесь класс `Some` находится в пакете `another.subpack`, 
его полное имя -- another.subpack.Some, он обязан находиться в файле `Some.java`,
а путь к этому файлу должен быть `another/subpack/Some.java`. 
Директория `another` должна быть поддиректорией Source root.

== Тела классов

На языке Java тела классов пишутся в фигурных скобках. В первую очередь, классы состоят из *полей* (данных) и *методов* (операций над данными).
*Метод* является синонимом *функции* (часто считается, что метод -- это функция, определённая внутри класса).
В классе `Hello` нет полей, и имеется один метод `main`:

[source,java]
----
    public static void main(String[] args) {
        System.out.println("Здравствуй, мир!);
    }
----

Модификатор _public_ задаёт видимость. Как мы уже видели раньше, _public_ -- это открытая видимость, то есть доступная всем.

=== Видимости

Всего в Java имеется четыре разных видимости:

* открытая _public_
* закрытая _private_ -- может использоваться только внутри класса, подобный член класса виден только внутри этого класса
* пакетно-закрытая -- не имеет модификатора, видна внутри того же класса, *а также* внутри того же пакета
* защищённая _protected_ -- также может использовать только внутри класса, видна внутри него же, внутри того же пакета, *а также* внутри наследников этого класса (о них поговорим позже)

Таким образом, видимостей имеется четыре, но модификаторов видимости всего три. Без модификатора считается, что видимость пакетно-закрытая (package private). Иногда программисты на Java подобную видимость подчёркивают комментарием:
[source,java]
----
// FILE: SomeClass.java
package test;

public class SomeClass {
}

/* package-private */ class AnotherClass {
}
----

Обратите внимание, что имя `SomeClass` обязано совпадать с именем файла (открытый класс), а имя `AnotherClass` -- нет.

Наиболее часто программисты используют закрытую видимость (для описания деталей реализации, которые не должны быть видны снаружи) и открытую видимость (для описания доступных всем действий с объектом). Если вы новичок в Java, неплохое правило на первое время -- делать закрытыми все поля и открытыми все методы (после этого можно закрыть все те методы, которые используются только внутри класса).
----

=== Статичность

[source,java]
----
    public static void main(String[] args) {
        System.out.println("Здравствуй, мир!);
    }
----

Как мы видим, функция `main` также является _static_, то есть статической. Чтобы понять, что это такое, нам придётся коснуться разницы между классами (class) и их *экземплярами* (class instance). Иногда вместо "экземпляр класса" говорят "объект класса".

