= Коллекции, итераторы, списки

Здесь мы начинаем рассматривать библиотеку коллекций Java. 

== Основные понятия

Библиотека коллекций строится на трёх видах кирпичей:

* *интерфейсы* `interface` определяют, что именно умеет делать тот или иной объект, но обычно ничего не говорят о том, как он это делает
* *абстрактные классы* `abstract class` содержат так называемую частичную реализацию объекта; в библиотеке коллекций они, как правило, реализуют все необходимые методы через несколько базовых
* *классы* `class` отвечают на вопрос о том, какие именно данные хранит объект и как именно он осуществляет те или иные операции

В прикладном коде интерфейсы обычно используются для определения типов переменных, параметров, полей, результатов методов; классы -- для создания объектов при вызове их конструкторов. Абстрактные классы в прикладном коде используются сравнительно редко, они позволяют за короткое время написать свою реализацию коллекции, если это потребовалось.

Для описания отношений вида *подтип*, *подвид* используется концепция *наследования*. В объектно-ориентированном программировании ситуация, когда класс (интерфейс) Б является *наследником* класса (интерфейса) А, означает, что:

* по смыслу объект типа Б является разновидностью объекта типа А
* объект типа Б можно употреблять везде, где нужен тип А
* объект типа Б содержит все данные, которые есть в объекте типа А (и, возможно, какие-либо другие)
* на объекте типа Б можно вызывать все методы, которые можно вызывать на объекте типа А (и, возможно, какие-либо другие)

Сокращённо говорят, что "public inheritance means IS A", или "открытое наследование означает ЭТО ЕСТЬ". В Java любое наследование считается открытым (в отличие от, например, С\+\+). Кроме этого, с наследованием связано ещё два специальных слова:

* про класс Б можно сказать, что он *расширяет* класс А или *реализует* интерфейс А (в обоих случаях он является наследником А)
* про интерфейс Б можно сказать, что он *расширяет* интерфейс А (и опять-таки это синоним слова "наследник")
* интерфейс Б никогда не может являться наследником класса А (запрещено правилами Java).
