= Командная строка, исключения

Внимание: этот раздел напрямую связан с выполнением второго практического задания. 
Пример его выполнения на Java и Kotlin см. 
https://github.com/Kotlin-Polytech/FromKotlinToJava/tree/master/src/part2/recode[в этом же репозитории]. 

== Консольное приложение (программа), основные понятия.

Это практическое задание будет первым для нас, где мы разрабатываем полноценное приложение (а не отдельную функцию или класс). Вопреки общепринятому мнению, консольных приложений сейчас разрабатывается довольно много. Часто вы пользуетесь ими, сами не замечая этого. Например, во время работы Intellij IDEA вы постоянно пользуетесь компилятором Java (javac), компилятором Kotlin (kotlinc), Git клиентом, Maven или Gradle клиентом и так далее. Все эти приложения -- консольные, а Intellij IDEA обеспечивает удобную графическую оболочку для взаимодействия с ними.

Что же такое "консольное приложение" и что такое консоль? Если объяснять на пальцах, то консольное приложение не использует графическую оболочку и какие-либо графические элементы. Для взаимодействия с пользователем (ввода-вывода) оно использует консоль -- место, куда выводится информация от приложения (например, с помощью функции `println`) и одновременно место, где пользователь по запросу от приложения может что-нибудь ответить (например, с помощью функции `readLine` в Kotlin или с помощью методов `System.in` в Java). Возможность ввода информации пользователем, впрочем, в современных консольных приложениях используется довольно редко.

Вы хотите увидеть, как выглядит консоль (она же -- терминал)? К ней можно получить доступ разными способами. Например, внутри Intellij IDEA доступ к ней обеспечивается комбинацией Alt-F12 (View > Tool Windows > Terminal), и там она имеет вид однотонного окна в нижней части экрана с приглашающей надписью вида 

```
Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\kotlin>
```

Консоль также появится в нижней части экрана, если в Intellij IDEA запустить какое-либо приложение или тест (выглядеть она будет при этом немножко по-другому). 

В ОС Windows вы можете открыть консоль через приложение `Command Prompt` (Главное меню Windows > Набрать `cmd`). Там она выглядит, как чёрное окно с заголовком Command Prompt и примерно теми же приглашающими надписями.

Как запустить консольное приложение? Сейчас, когда мы хотим запустить какую-то программу, в 99% случаях мы это делаем щелчком по ярлыку. В принципе, ярлык можно создать и для консольного приложения, но чаще оно запускается напрямую из консоли. Как это делается? Нужно выполнить следующие действия:

. Открыть консоль (одним из способов, перечисленных выше).
. Перейти в директорию, где находится файл, запускающий приложение. Приглашение вида `G:\kotlin` указывает, в какой директории консоль находится сейчас. Переход в другую директорию делается (в ОС Windows) командой вида `cd D:\User\Projects\SomeProject`.
. Запустить файл с приложением. В ОС Windows такие *исполняемые* файлы обычно имеют расширение `.exe`, `.com` или `.bat`. Для этого в консоли набираются команда вида `SomeProject.exe` или просто `SomeProject`.

*Внимание!* Для консольного приложения под JVM (написанного, например, на Java, Kotlin или Scala) третий пункт будет выглядеть несколько по-другому. Всё дело в том, что такие приложения не предназначены для их запуска в операционной системе напрямую, и поэтому компиляторы Java или Kotlin не создают в процессе своей работы исполняемые файлы с расширением `.exe`. Вместо этого, генерируются два других вида файлов:

* `.class` файлы содержат скомпилированные в *байт-код JVM* классы. Для одного *класса* на Java создаётся один `.class` файл, причём это касается не только классов верхнего уровня, но и вложенных или локальных. Иногда компилятор может создавать дополнительные `.class` файлы, вообще не соответствующие ни одному из присутствующих в коде классов. Компилятор Kotlin дополнительно создаёт один `.class` файл для каждого файла на Kotlin, в котором присутствуют функции верхнего уровня или глобальные переменные (свойства). 
* `.jar` файл является архивом, в который упаковываются все `.class` файлы, появившиеся в результате компиляции вашей программы. Этот файл -- самый близкий аналог исполняемого файла, но не для операционной системы, а для JVM.

Как же запустить JVM-приложение с помощью jar-файла? Для этого в консоли (вместо третьего пункта выше) вы набираете:

```
java -jar SomeProject.jar
```

Здесь `java.exe` -- исполняемый файл виртуальной машины Java (Java Virtual Machine, JVM -- отметим, что и она, в данном случае, является аналогом консольного приложения). Этот файл обычно находится в директории вида `C:\Program Files\Java\jdk-11.0.5\bin` (точный путь зависит от вашей версии JDK и места её установки). Естественно, что ваш jar-файл будет находиться в другой директории и запускать эту команду вы будете из неё -- как же ОС Windows сможет найти исполняемый файл `java.exe`? 

А ответ таков -- через переменную окружения `PATH`. Это переменная *не программы*, а операционной системы. Доступ к ней вы можете получить, нажав Windows-Pause, затем войдя в Advanced System Settings и Environment Variables. В появившемся окне, в нижней его части вы найдёте переменную `Path` или `PATH`. Её значение -- это список директорий, разделённых точкой с запятой, в которых ОС Windows ищет исполняемые файлы программ. Вам необходимо добавить туда директорию, где находится `java.exe` (см. абзац выше).

== Аргументы командной строки

Выше я упомянул, что современные консольные приложения редко используют возможность ввода информации пользователем. Логичный вопрос -- как же тогда они понимают, что именно им делать? Ответ на него -- для этой цели они используют *аргументы командной строки*. Откуда они берутся? Пользователь их вводит, когда запускает консольное приложение. Например, выше в строке `java -jar SomeProject.jar` суффикс `-jar SomeProject.jar` это как раз и есть аргументы командной строки для приложения `java.exe`, при этом программа `java.exe` будет считать `-jar` нулевым аргументом, а `SomeProject.jar` первым, то есть отдельные аргументы разделяются пробелами. В данном случае нулевой аргумент означает, что JVM должна запустить на исполнение именно jar-файл, а первый задаёт конкретное имя этого jar-файла.

*Прочитать* свои аргументы командной строки JVM-приложение может через главную функцию `main`. На Java её заголовок выглядит так:

[source,java]
----
public class SomeClass {
    public static void main(String[] args) {
        // args[0] = нулевой аргумент командной строки, 
        // args[1] = первый и т.д., 
        // args.length = число заданных аргументов
    }
}
----

А на Kotlin вот так:

[source,kotlin]
----
fun main(args: Array<String>) {
    // Смысл args тот же самый
}
----

Для запуска вашей программы с аргументами командной строки из консоли вы набираете:

```
java -jar SomeProject.jar SomeProjectArgument0 SomeProjectArgument1
```

указывая нужное вам число аргументов после `SomeProject.jar`. JVM при запуске автоматически передаст эти аргументы главной функции вашего приложения.

Вы также можете запустить свою программу из Intellij IDEA напрямую, без создания консоли, но и здесь потребуются некоторые ухищрения. Если вы попробуете запустить свою программу, нажав на "зелёный треугольник" напротив главной функции, то запуск произойдёт, но аргументы командной строки в программу переданы не будут (`args.length` будет равно 0) и, если ваша программа ожидает их наличия, в ней произойдёт ошибка. Для того чтобы аргументы командной строки всё-таки передать, необходимо создать так называемую "конфигурацию запуска" (Run Configuration). Для этого: 

. Вначале запустите программу с помощью "зелёного треугольника" обычным образом.
. После этого в верхней правой части окна IDEA найдите выпадающее меню (Combo Box) слева от иконки с зелёным треугольником, откройте его и выберите пункт "Edit Configurations". 
. В открывшемся окне слева выберите Application > <Название вашего класса или файла с функцией main>, как правило эти пункты будут сверху списка конфигураций. Если ваша программа на Kotlin и файл с главной функцией назывался `Some.kt`, это название будет `SomeKt`, на Java название конфигурации в точности соответствует названию класса с главной функцией. 
. Заполните пункт `Program arguments`, указав в нём нужные вам аргументы командной строки.
. Нажмите OK.
. Нажмите на "зелёный треугольник", но не напротив главной функции, а рядом с выпадающим меню, в которое вы только что входили.

Если вы всё сделали правильно, программа запустится с теми аргументами командной строки, которые вы указали.
