= Командная строка, исключения

Внимание: этот раздел напрямую связан с выполнением второго практического задания. 
Пример его выполнения на Java и Kotlin см. 
https://github.com/Kotlin-Polytech/FromKotlinToJava/tree/master/src/part2/recode[в этом же репозитории]. 

== Консольное приложение (программа). Основные понятия.

Это практическое задание будет первым для нас, где мы разрабатываем полноценное приложение (а не отдельную функцию или класс). Вопреки общепринятому мнению, консольных приложений сейчас разрабатывается довольно много. Часто вы пользуетесь ими, сами не замечая этого. Например, во время работы Intellij IDEA вы постоянно пользуетесь компилятором Java (javac), компилятором Kotlin (kotlinc), Git клиентом, Maven или Gradle клиентом и так далее. Все эти приложения -- консольные, а Intellij IDEA обеспечивает удобную графическую оболочку для взаимодействия с ними.

Что же такое "консольное приложение" и что такое консоль? Если объяснять на пальцах, то консольное приложение не использует графическую оболочку и какие-либо графические элементы. Для взаимодействия с пользователем (ввода-вывода) оно использует консоль -- место, куда выводится информация от приложения (например, с помощью функции `println`) и одновременно место, где пользователь по запросу от приложения может что-нибудь ответить (например, с помощью функции `readLine` в Kotlin или с помощью методов `System.in` в Java). Возможность ввода информации пользователем, впрочем, в современных консольных приложениях используется довольно редко.

Вы хотите увидеть, как выглядит консоль (она же -- терминал)? К ней можно получить доступ разными способами. Например, внутри Intellij IDEA доступ к ней обеспечивается комбинацией Alt-F12 (View > Tool Windows > Terminal), и там она имеет вид однотонного окна в нижней части экрана с приглашающей надписью вида 

```
Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\kotlin>
```

Консоль также появится в нижней части экрана, если в Intellij IDEA запустить какое-либо приложение или тест (выглядеть она будет при этом немножко по другому). 

В ОС Windows вы можете открыть консоль через приложение `Command Prompt` (Главное меню Windows > Набрать cmd). Там она выглядит, как чёрное окно с заголовком Command Prompt и примерно теми же приглашающими надписями.

Как запустить консольное приложение? Сейчас, когда мы хотим запустить какую-то программу, в 99% случаях мы это делаем щелчком по ярлыку. В принципе, ярлык можно создать и для консольного приложения, но чаще оно запускается напрямую из консоли. Как это делается? Нужно выполнить следующие действия:

. Открыть консоль (одним из способов, перечисленных выше).
. Перейти в директорию, где находится файл, запускающий приложение. Приглашение вида `G:\kotlin` указывает, в какой директории консоль находится сейчас. Переход в другую директорию делается (в ОС Windows) командой вида `cd D:\User\Projects\SomeProject`.
. Запустить файл с приложением. В ОС Windows такие файлы обычно имеют расширение `.exe`, `.com` или `.bat`. Для этого в консоли набираются команда вида `SomeProject.exe`.

== Аргументы командной строки

Выше я упомянул, что современные консольные приложения редко используют возможность ввода информации пользователем. Логичный вопрос -- как же тогда они понимают, что именно им делать? Ответ на него -- для этой цели они используют *аргументы командной строки*. Откуда они берутся? Пользователь их вводит, когда запускает консольное приложение. 
