= Командная строка, исключения

Внимание: этот раздел напрямую связан с выполнением второго практического задания. 
Пример его выполнения на Java и Kotlin см. 
https://github.com/Kotlin-Polytech/FromKotlinToJava/tree/master/src/part2/recode[в этом же репозитории]. 

== Консольное приложение (программа). Основные понятия.

Это практическое задание будет первым для нас, где мы разрабатываем полноценное приложение (а не отдельную функцию или класс). Вопреки общепринятому мнению, консольных приложений сейчас разрабатывается довольно много. Часто вы пользуетесь ими, сами не замечая этого. Например, во время работы Intellij IDEA вы постоянно пользуетесь компилятором Java (javac), компилятором Kotlin (kotlinc), Git клиентом, Maven или Gradle клиентом и так далее. Все эти приложения -- консольные, а Intellij IDEA обеспечивает удобную графическую оболочку для взаимодействия с ними.

Что же такое "консольное приложение" и что такое консоль? Если объяснять на пальцах, то консольное приложение не использует графическую оболочку и какие-либо графические элементы. Для взаимодействия с пользователем (ввода-вывода) оно использует консоль -- место, куда выводится информация от приложения (например, с помощью функции `println`) и одновременно место, где пользователь по запросу от приложения может что-нибудь ответить (например, с помощью функции `readLine` в Kotlin или с помощью методов `System.in` в Java). Возможность ввода информации пользователем, впрочем, в современных консольных приложениях используется довольно редко.

Вы хотите увидеть, как выглядит консоль (она же -- терминал)? К ней можно получить доступ разными способами. Например, внутри Intellij IDEA доступ к ней обеспечивается комбинацией Alt-F12 (View > Tool Windows > Terminal), и там она имеет вид однотонного окна в нижней части экрана с приглашающей надписью вида 

```
Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\kotlin>
```

Консоль также появится в нижней части экрана, если в Intellij IDEA запустить какое-либо приложение или тест (выглядеть она будет при этом немножко по другому). 

В ОС Windows вы можете открыть консоль через приложение `Command Prompt` (Главное меню Windows > Набрать cmd). Там она выглядит, как чёрное окно с заголовком Command Prompt и примерно теми же приглашающими надписями.
