= Шаблонные (generic) классы

== Общие принципы

Любой класс, имеющий хотя бы один *типовой параметр*, вроде `<T>`, называется шаблонным (generic). Такие примеры мы много раз встречали в библиотеке коллекций -- например, `ArrayList<E>` или `HashMap<K, V>`. Шаблонные классы позволяют нам, в частности, создавать контейнеры из элементов заданного типа. Когда мы используем шаблонный класс для определения типа, нам необходимо указать его *типовой аргумент*. 

=== Типовые аргументы на Java

 * `List<String> list = ...` -- мы указываем конкретный аргумент, получая список именно из строк и это самый распространённый случай
 * `List list = ...` -- мы не указываем аргумент, создавая так называемый *Raw type* (сырой тип). Это legacy код (это означает, что он поддерживается исключительно для совместимости со старыми версиями Java, в которых шаблонных классов не было в принципе). Для использования в новом коде не рекомендуется.
 * `List<?> list = ...` -- мы используем джокер `?`, создавая так называемый *Wildcard type* (подстановочный тип), соответствующий произвольному списку. На первый взгляд кажется, что по смыслу он близок к сырому типу, но на самом деле такой тип гораздо более безопасен.

=== Типовые аргументы на Kotlin

 * `val list: List<String>` -- неизменяемый список строк
 * `val list: List<*>` -- Wildcard type

== Вспомним наследование...

... и правила, с ним связанные. Возьмём пример:

[source,java]
----
public interface Animal {
    void move();
}
public interface Horse extends Animal {
    void run();
}
----

Здесь интерфейс `Horse` наследует (расширяет) интерфейс `Animal`. С точки зрения правил наследования это означает, что:

 * Horse is an Animal (лошадь является животным)
 * Лошадь может использоваться везде, где ожидается животное
 
В частности, допустим вот такой код
[source,java]
----
// ... in some class ...
public void test(Horse horse) {
    horse.move() // Лошадь тоже умеет ходить
    feed(horse) // Лошадь тоже можно кормить
    Animal animal = horse; // Лошадь является животным
}
public void feed(Animal animal) {
    // ...
}
----

== Инвариантность и ковариантность в Java

Чтобы лучше понять, как все эти штуки работают, рассмотрим пример:

[source,java]
----
// ... in some class ...
public void test() {
    // При вызове конструктора, мы просим компилятор вывести типовой аргумент ArrayList
    List<Animal> animals = new ArrayList<>(); 
    // Является ли список животных списком объектов?
    List<Object> objects = animals; 
    // Можно ли в список объектов добавить строку?
    objects.add("Some string"); 
    // А здесь что происходит? Можно ли так?
    animals.get(0).move(); 
}
----

Анализируя пример, заметим, что животное (Animal) является объектом -- им является любой ссылочный тип в Java. А является ли список животных списком объектов? Если да, то присваивание `objects = animals` возможно. Допустим пока, что это так.

Ответ на следующий вопрос очевидно положительный. В список объектов можно добавить объект. Строка -- это объект. Значит, её можно использовать везде, где можно использовать объект.

Наконец, что происходит в последней строчке кода? Ссылочные переменные `animals` и `objects` указывают на один и тот же список. В этот список был добавлен один объект, его реальный тип -- строка (String). Мы достаём его из списка с помощью `get(0)`. Раз `animals` является списком животных, значит, компилятор думает, что достанем мы животное. А животное может ходить (move). Теоретически этот код верен, практически же строка (String) не является животным (Animal) и не может ходить. Где же ошибка?

Если представить, что этот код компилируется верно, в последней его строчке очевидно должна произойти ошибка во время выполнения. Реально же ошибка в нём есть, и она заключается в том, что список животных *не является* списком объектов, точно так же как список лошадей *не является* списком животных. Вообще, любой список (при явном указании типа элементов) можно использовать вместо другого только в том случае, если тип элементов у них одинаковый. Это свойство списков (и шаблонных классов Java вообще) называется *инвариантностью* (invariant).

[source,java]
----
// ... in some class ...
public void test() {
    List<Animal> animals = new ArrayList<>(); 
    List<Object> objects = animals; // ERROR: incompatible types
    objects.add("Some string"); 
    animals.get(0).move(); 
}
----

Для сравнения, массивы в Java ведут себя не так:

[source,java]
----
// ... in some class ...
public void test() {
    Animal[] animals = new Animal[10]; 
    Object[] objects = animals; // OK: массивы ковариантны
    objects[0] = "Some string"; // OK in compile-time: String is an Object
    animals[0].move();          // OK in compile-time: Animal can move
}
----

Массивы, в отличие от шаблонных классов, в Java *ковариантны* (covariant). Это означает, что если лошадь является животным, то и массив лошадей является массивом животных. На практике (как в примере) это может приводить к проблемам при записи в массив: при выполнении строчки `objects[0] = "Some string"` мы получим исключение `ArrayStoreException`. Почему?

Вторым свойством массивов в Java является сохранение данных о реальном типе их элементов во время выполнения программы. По научному говорят так: Arrays in Java are *reified* (реифицированные, овеществлённые). Это означает, что массив `objects` всё ещё знает о том, что хранимый тип элементов в нём -- `Animal`, и при попытке записать туда несовместимую строку происходит исключение.

А верно ли, что Lists (Generics) in Java are reified? Нет, это не так, и это второе отличие массивов от шаблонов. Про шаблонные классы в Java говорят: Generics in Java are *erased* (стираемые) или, более точно, Generics in Java have *erased* type parameters (типовые параметры шаблонных классов стираемые). Здесь получается, что слова *reified* и *erased* являются антонимами и относятся к типу элементов -- в первом случае во время выполнения программы мы знаем его, во втором случае нет. Все списки в Java во время выполнения считают, что тип их хранимых элементов `Object`, а контроль типов элементов выполняется *исключительно* при компиляции.

== Инвариантность и ковариантность в Kotlin

Как же меняется поведение в Kotlin? Довольно существенно. Во-первых на нём тип `Array<T>` (массив) -- это тоже шаблон. И он инвариантен, как и все шаблоны -- по умолчанию.

[source,kotlin]
----
fun test(animals: Array<Animal>) {
    val objects: Array<Any> = animals // ERROR: type mismatch
}
----

Во-вторых, неизменяемый список `List<T>` в Kotlin *ковариантен*, а изменяемый `MutableList<T>` *инвариантен*. Как этого добились в Kotlin? Дело в том, что заголовки списков выглядят так:

[source,kotlin]
----
// out ~ covariant
interface List<out T> { ... }
// no modifier ~ invariant
interface MutableList<T> : List<T> { ... }
----

И действительно, в этом примере

[source,java]
----
// ... in some class ...
public void test() {
    List<Animal> animals = new ArrayList<>(); 
    List<Object> objects = animals; // ERROR: type mismatch
    objects.add("Some string"); 
    animals.get(0).move(); 
}
----

проблемы возникают только потому, что мы пытаемся что-то в список записать. Если же этого не делать, то всё в порядке:

[source,kotlin]
----
fun test(animals: List<Animal>) {
    val objects: List<Any> = animals // OK, List is covariant
    objects[0].toString()               // OK: у животного, как и у любого объекта, есть toString()
    objects[0] = "Some string"          // ERROR: List is immutable
}
----

== Raw Types

Как я уже говорил, сырые типы -- наследие (legacy) старых версий Java. Шаблонные классы появились в пятой (1.5) версии Java, до этого момента коллекции были обычными классами, типовые параметры и аргументы не указывались. Например:

[source,java]
----
// ... in some class ...
public void test(Horse horse) {
    List animals = new ArrayList();   // Программист надеется, что по названию запомнит, что это животные...
    animals.add(horse);               // WARNING: unchecked call
    ((Animal) animals.get(0)).move(); // Приходится всюду писать преобразования типов...
    use(animals);                     // OK (здесь список и там список)
    ((Animal) animals.get(1)).move(); // Внезапно, ClassCastException -- там оказалась строка...
}
public void use(List objects) {
    objects.add("42");  // OOPS! Мы забыли, что тут были животные, а не просто объекты...
}
----

Подобный код будет компилироваться и в нынешней версии Java, однако вы получите ряд предупреждений об так называемых unchecked call -- вызовах без проверок типов элементов. Минусы их должны быть видны из этого примера -- лишние, а иногда и небезопасные, преобразования типов. Проблемы, которые шаблонные классы при явном указании типа элементов позволяют находить во время компиляции, здесь находятся только во время выполнения программы, что всегда хуже.

С точки зрения системы типов сырой список совместим с любым списком, что тоже отрицательно влияет на безопасность. Например:

[source,java]
----
// ... in some class ...
public void test() {
    List<Animal> animals = new ArrayList<>();
    List objects = animals;         
    List<String> strings = objects; // WARNING: unchecked assignment
}
----

В этом коде мы получим предупреждение, но он компилируется. В результате компилятор думает, что `strings` содержит строки, хотя на самом деле это не так. Это легко позволяет вызвать ошибку во время выполнения (добейтесь это сами, пожалуйста).

== Литература для самостоятельного чтения

Effective Java. Joshua Bloch (номера глав даю по второму изданию):

 23. Don't use raw types in new code.
 25. Prefer lists to arrays.
 26. Favor generic types.
 28. Use bounded wildcards to increase API flexibility.

https://kotlinlang.org/docs/reference/generics.html[Kotlin generics: in, out where]
