= Шаблонные (generic) классы

== Общие принципы

Любой класс, имеющий хотя бы один *типовой параметр*, вроде `<T>`, называется шаблонным (generic). Такие примеры мы много раз встречали в библиотеке коллекций -- например, `ArrayList<E>` или `HashMap<K, V>`. Шаблонные классы позволяют нам, в частности, создавать контейнеры из элементов заданного типа. Когда мы используем шаблонный класс для определения типа, нам необходимо указать его *типовой аргумент*. 

=== Типовые аргументы на Java

 * `List<String> list = ...` -- мы указываем конкретный аргумент, получая список именно из строк и это самый распространённый случай
 * `List list = ...` -- мы не указываем аргумент, создавая так называемый *Raw type* (сырой тип). Это legacy код (это означает, что он поддерживается исключительно для совместимости со старыми версиями Java, в которых шаблонных классов не было в принципе). Для использования в новом коде не рекомендуется.
 * `List<?> list = ...` -- мы используем джокер `?`, создавая так называемый *Wildcard type* (подстановочный тип), соответствующий произвольному списку. На первый взгляд кажется, что по смыслу он близок к сырому типу, но на самом деле такой тип гораздо более безопасен.

=== Типовые аргументы на Kotlin

 * `val list: List<String>` -- неизменяемый список строк
 * `val list: List<*>` -- Wildcard type

== Инвариантность и ковариантность

Чтобы лучше понять, как все эти штуки работают, рассмотрим пример:

[source,java]
----
public interface Animal {
    void move();
}
// ... in some class ...
public void test() {
    // При вызове конструктора, мы просим компилятор вывести типовой аргумент ArrayList
    List<Animal> animals = new ArrayList<>(); 
    // Является ли список животных списком объектов?
    List<Object> objects = animals; 
    // Можно ли в список объектов добавить строку?
    objects.add("Some string"); 
    // А здесь что происходит? Можно ли так?
    animals.get(0).move(); 
}
----

Анализируя пример, заметим, что животное (Animal) является объектом -- им является любой ссылочный тип в Java. А является ли список животных списком объектов? Если да, то присваивание `objects = animals` возможно. Допустим пока, что это так.

Ответ на следующий вопрос очевидно положительный. В список объектов можно добавить объект. Строка -- это объект. Значит, её можно использовать везде, где можно использовать объект.

Наконец, что происходит в последней строчке кода? Ссылочные переменные `animals` и `objects` указывают на один и тот же список. В этот список был добавлен один объект, его реальный тип -- строка (String). Мы достаём его из списка с помощью `get(0)`. Раз `animals` является списком животных, значит, компилятор думает, что достанем мы животное. А животное может ходить (move). Теоретически этот код верен, практически же строка (String) не является животным (Animal) и не может ходить. Где же ошибка?
