= JavaFX-приложения с графическим интерфейсом

Сегодня мы поговорим о приложениях, созданных с помощью библиотеки JavaFX. Эта библиотека появилась в 2007 году, она предназначена для проектирования приложений с графическим интерфейсом -- как Desktop-приложений (работающих на обычном компьютере), так и Web-приложений (работающих в браузере). Библиотека была призвана заменить GUI-библиотеку предыдущего поколения -- Swing. Первые годы JavaFX существовала отдельно от основной платформы Java, и язык для её программирования назывался JavaFX Script. В 2014 году библиотека вошла в состав JDK 1.8 и получила полноценную поддержку со стороны языка Java.

== Поддержка на Java и Kotlin

Библиотека JavaFX входит в состав JDK 1.8 и более поздних, поэтому программы на Java и Kotlin могут, в принципе, использовать её без подключения дополнительных зависимостей. Для программ на Kotlin, однако, существует удобный DSL (Domain Specific Language = предметно-ориентированный язык) https://tornadofx.io[tornadofx] -- см. также https://github.com/edvin/tornadofx[его GitHub-репозиторий]. Этот DSL может быть подключен к программам на Kotlin как дополнительная библиотека -- подробности о подключении дополнительных библиотек см. в https://github.com/Kotlin-Polytech/FromKotlinToJava/tree/master/tutorial/07_Console_Exceptions.adoc[7-м разделе].

Domain Specific Language позволяет, в частности, описывать структуру JavaFX-сцен в более прозрачной для программиста форме. Вот так, например, выглядит типичное описание диалога с помощью tornadofx (пример взят из https://github.com/Kotlin-Polytech/FromKotlinToJava/blob/master/src/part3/fourinrow/javafx/ChoosePlayerDialog.kt[игры 4 в ряд]).

[source,kotlin]
----
    init {
        title = "Four-in-Row"
        with (dialogPane) {
            headerText = "Choose players"
            buttonTypes.add(ButtonType("Start Game", ButtonBar.ButtonData.OK_DONE))
            buttonTypes.add(ButtonType("Quit", ButtonBar.ButtonData.CANCEL_CLOSE))
            content = hbox {
                vbox {
                    label("Yellow")
                    togglegroup {
                        bind(yellowPlayer)
                        radiobutton("Human") {
                            isSelected = true
                        }
                        radiobutton("Computer")
                    }
                }
                spacer(Priority.ALWAYS)
                vbox {
                    label("Red")
                    togglegroup {
                        bind(redPlayer)
                        radiobutton("Human")
                        radiobutton("Computer") {
                            isSelected = true
                        }
                    }
                }
            }
        }
    }
----

Прочитав этот фрагмент кода, мы можем узнать:

* Диалог называется Choose Players
* Диалог имеет две кнопки, позволяющие его покинуть -- Start Game(OK) и Quit(CANCEL)
* Основная часть диалога -- горизонтальная секция (hbox == horizontal box), состоящая, в свою очередь, из двух вертикальных секций (vbox == vertical box)
* Левая вертикальная секция помечена (label) как Yellow и включает в себя группу из двух радио-кнопок (radiobutton) -- из этих кнопок пользователь всегда сможет выбрать только одну. По умолчанию из кнопок Human и Computer выбрана Human
* Правая вертикальная секция помечена как Red и включает в себя две такие же кнопки, но по умолчанию выбрана Computer

== Архитектура GUI-приложений

Когда мы разрабатываем GUI-приложение (GUI = Graphical User Interface), важной задачей является отделение внутренней логики приложения от его графической части. Применительно к языкам Java и Kotlin удобно, например, поместить внутреннюю логику в отдельный пакет и полностью абстрагировать её от графической части -- например, не применять классы и функции из пакетов `javafx.*` и `tornadofx.*`. Это позволяет, в частности:

* разрабатывать и тестировать внутреннюю логику приложения отдельно от его графических функций
* менять графическую часть приложения (в том числе, используемую библиотеку) без значительного изменения внутренней логики

Общеизвестным *шаблоном* (pattern), реализующим подобную архитектуру, является MVC = Model-View-Controller (модель-представление-контроллер). 



